# Generated by Django 2.2 on 2019-05-27 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190527_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelation',
            name='fans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foces', to=settings.AUTH_USER_MODEL, verbose_name='粉丝'),
        ),
        migrations.AlterField(
            model_name='userrelation',
            name='focus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fans', to=settings.AUTH_USER_MODEL, verbose_name='关注'),
        ),
        migrations.AlterUniqueTogether(
            name='userrelation',
            unique_together={('focus', 'fans')},
        ),
    ]
