# Generated by Django 2.2 on 2019-06-03 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190527_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelation',
            name='fans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus', to=settings.AUTH_USER_MODEL, verbose_name='粉丝'),
        ),
    ]
