# Generated by Django 2.1.7 on 2019-03-22 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='titile',
            new_name='title',
        ),
    ]
