# Generated by Django 2.1.7 on 2019-03-13 14:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='ArticleColumn',
        ),
        migrations.AlterModelOptions(
            name='articlecolumn',
            options={'verbose_name': '文章信息', 'verbose_name_plural': '文章信息'},
        ),
    ]
