# Generated by Django 2.2 on 2019-05-22 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[(1, '关注'), (2, '评论'), (3, '点赞'), (4, '留言'), (5, '系统通知')], default=5, max_length=6, verbose_name='类型')),
                ('body', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('created', models.DateTimeField(auto_now=True, db_index=True, verbose_name='创建时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '站内消息',
                'verbose_name_plural': '站内消息',
                'db_table': 'blogmessages',
                'ordering': ['-created'],
            },
        ),
    ]
