# Generated by Django 2.2 on 2019-05-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmessages',
            name='item',
            field=models.CharField(choices=[('1', '关注'), ('2', '评论'), ('3', '点赞'), ('4', '留言'), ('5', '系统通知')], default='5', max_length=6, verbose_name='类型'),
        ),
    ]
