# Generated by Django 2.0 on 2018-02-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dbServer',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.GenericIPAddressField(default='127.0.0.1', unique=True)),
                ('port', models.IntegerField(default=7800)),
                ('username', models.CharField(max_length=128, null=True)),
                ('passwd', models.CharField(max_length=256, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '数据库',
                'verbose_name_plural': '数据库列表',
                'ordering': ['pid', 'ctime'],
                'get_latest_by': 'ctime',
            },
        ),
    ]
