# Generated by Django 2.0 on 2018-02-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebRedis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbserver',
            name='passwd',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='dbserver',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
