# Generated by Django 2.0 on 2018-02-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebRedis', '0002_auto_20180202_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbserver',
            name='describtion',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
