# Generated by Django 2.0 on 2018-02-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebRedis', '0003_dbserver_describtion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbserver',
            name='host',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
        migrations.AlterUniqueTogether(
            name='dbserver',
            unique_together={('host', 'port')},
        ),
    ]
