# Generated by Django 2.0 on 2018-02-02 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebRedis', '0004_auto_20180202_1518'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dbServer',
        ),
    ]
