# Generated by Django 2.0 on 2018-02-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WebRedis', '0005_delete_dbserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='dbServer',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.GenericIPAddressField(default='127.0.0.1')),
                ('port', models.IntegerField(default=7800)),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('passwd', models.CharField(blank=True, max_length=256, null=True)),
                ('describtion', models.TextField(blank=True, max_length=512, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '数据库',
                'verbose_name_plural': '数据库列表',
                'ordering': ['pid', 'ctime'],
                'get_latest_by': 'ctime',
            },
        ),
        migrations.AlterUniqueTogether(
            name='dbserver',
            unique_together={('host', 'port')},
        ),
    ]
