# Generated by Django 2.0 on 2018-02-02 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebRedis', '0006_auto_20180202_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbserver',
            options={'get_latest_by': 'ctime', 'ordering': ['pid', 'ctime'], 'verbose_name': '数据库', 'verbose_name_plural': 'Redis数据库列表'},
        ),
    ]
