# Generated by Django 2.0 on 2018-02-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebRedis', '0007_auto_20180202_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbserver',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='dbserver',
            name='describtion',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='dbserver',
            name='host',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='dbserver',
            name='passwd',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='dbserver',
            name='port',
            field=models.IntegerField(default=7800, verbose_name='端口号'),
        ),
        migrations.AlterField(
            model_name='dbserver',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='用户名'),
        ),
    ]
