# Generated by Django 2.0 on 2018-02-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebRedis', '0008_auto_20180202_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbserver',
            name='pid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='序号'),
        ),
    ]
