# Generated by Django 2.0 on 2018-02-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebRedis', '0009_auto_20180202_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbserver',
            name='status',
            field=models.CharField(blank=True, choices=[('正常', 0), ('异常', 1)], default='正常', max_length=64, verbose_name='状态'),
        ),
    ]
