# Generated by Django 2.0 on 2018-02-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebRedis', '0010_dbserver_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbserver',
            name='status',
            field=models.CharField(blank=True, choices=[(0, '正常'), (1, '异常')], default='正常', max_length=64, verbose_name='状态'),
        ),
    ]
