# Generated by Django 2.0 on 2018-02-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebRedis', '0011_auto_20180202_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbserver',
            name='status',
            field=models.CharField(choices=[(0, '正常'), (1, '异常')], default=0, max_length=64, verbose_name='状态'),
        ),
    ]
