# Generated by Django 2.0 on 2018-02-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebRedis', '0015_auto_20180202_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbserver',
            name='describtion',
            field=models.TextField(blank=True, max_length=128, null=True, verbose_name='描述'),
        ),
    ]
