# Generated by Django 2.0 on 2018-02-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebRedis', '0016_auto_20180202_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbserver',
            name='describtion',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='描述'),
        ),
    ]
