# Generated by Django 2.0 on 2018-02-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebRedis', '0017_auto_20180205_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbserver',
            name='status',
            field=models.CharField(choices=[(True, '正常'), (False, '异常')], default=True, max_length=64, verbose_name='状态'),
        ),
    ]
