# Generated by Django 2.0 on 2018-02-08 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebRedis', '0019_auto_20180205_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbserver',
            options={'get_latest_by': 'ctime', 'ordering': ['pid', 'host', 'ctime'], 'verbose_name': '数据库', 'verbose_name_plural': 'Redis数据库列表'},
        ),
    ]
