# Generated by Django 2.0 on 2018-02-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebRedis', '0020_auto_20180208_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbserver',
            name='count',
            field=models.BigIntegerField(default=0, max_length=256, verbose_name='数据量'),
        ),
    ]
