# Generated by Django 2.1.7 on 2019-03-27 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUserDetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='电话')),
                ('profession', models.CharField(blank=True, max_length=200, null=True, verbose_name='电话')),
                ('company', models.CharField(blank=True, max_length=200, null=True, verbose_name='公司')),
                ('school', models.CharField(blank=True, max_length=200, null=True, verbose_name='学校')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='个人简介')),
            ],
            options={
                'verbose_name': '基本资料',
                'verbose_name_plural': '基本资料',
            },
        ),
        migrations.CreateModel(
            name='AccountUserProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=2, verbose_name='性别')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='注册日期')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='账户')),
            ],
            options={
                'verbose_name': '基本资料',
                'verbose_name_plural': '基本资料',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='accountuserdetailmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.AccountUserProfileModel', verbose_name='账户'),
        ),
    ]
