# Generated by Django 2.1.7 on 2019-03-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountuserdetailmodel',
            options={'verbose_name': '详细资料', 'verbose_name_plural': '详细资料'},
        ),
        migrations.AlterField(
            model_name='accountuserprofilemodel',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10, verbose_name='性别'),
        ),
    ]
