# Generated by Django 2.1.7 on 2019-03-27 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190327_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuserdetailmodel',
            name='profession',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='accountuserdetailmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.AccountUserProfileModel', to_field='user', verbose_name='账户'),
        ),
    ]
