# Generated by Django 2.1.7 on 2019-03-14 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190313_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '基本信息', 'verbose_name_plural': '基本信息'},
        ),
    ]
