# Generated by Django 2.1.7 on 2019-03-28 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190328_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuserdetailmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_detail', to='account.AccountUserProfileModel', verbose_name='账户'),
        ),
    ]
