# Generated by Django 2.0.3 on 2018-04-26 01:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedisHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.GenericIPAddressField(verbose_name='IP地址')),
                ('port', models.PositiveIntegerField(error_messages={'c1': '端口号为1~65536间的数字'}, validators=[django.core.validators.RegexValidator(code='c1', message='端口号为1~65536间的数字', regex='(^6[0-5]{2}[0-3][0-5]$)|(^[0-5][0-9]{4}$)|(^[1-9][0-9]{0,3}$)')], verbose_name='端口号')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='服务器名')),
                ('user', models.CharField(blank=True, max_length=128, verbose_name='用户名')),
                ('pwd', models.CharField(blank=True, max_length=256, verbose_name='密码')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='数据量')),
                ('describtion', models.TextField(blank=True, max_length=512, verbose_name='描述')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '数据服',
                'verbose_name_plural': '数据服列表',
                'db_table': 'WebRedis_RedisList',
            },
        ),
        migrations.CreateModel(
            name='UserInfoHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=128, unique=True, verbose_name='账号')),
                ('pwd', models.CharField(max_length=256, verbose_name='密码')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='请输入正确电话号码', regex='^1\\d{10}$|^+86-1\\d{10}$')], verbose_name='电话号码')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='邮箱')),
                ('limits', models.PositiveIntegerField(default=0, verbose_name='权限')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户列表',
                'db_table': 'WebRedis_UserInfo',
            },
        ),
        migrations.AddField(
            model_name='redishandler',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebRedis.UserInfoHandler', verbose_name='添加人'),
        ),
        migrations.AlterUniqueTogether(
            name='redishandler',
            unique_together={('host', 'port')},
        ),
    ]
