# Generated by Django 2.2 on 2019-05-22 16:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleColumns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=200, verbose_name='栏目')),
                ('created', models.DateTimeField(default=datetime.datetime(2019, 5, 22, 16, 44, 13, 31000), verbose_name='创建时间')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '栏目信息',
                'verbose_name_plural': '栏目信息',
                'db_table': 'articlecolumns',
                'ordering': ['-update'],
            },
        ),
        migrations.CreateModel(
            name='ArticleTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=200, verbose_name='关键字')),
                ('created', models.DateTimeField(default=datetime.datetime(2019, 5, 22, 16, 44, 13, 31000), verbose_name='创建时间')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '关键字',
                'verbose_name_plural': '关键字',
                'db_table': 'articletags',
                'ordering': ['-update'],
                'unique_together': {('author', 'body')},
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('body', models.TextField(verbose_name='内容')),
                ('slug', models.SlugField(max_length=200, verbose_name='访问地址')),
                ('created', models.DateTimeField(default=datetime.datetime(2019, 5, 22, 16, 44, 13, 32000), verbose_name='创建时间')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('column', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.ArticleColumns', verbose_name='栏目')),
                ('favorites', models.ManyToManyField(blank=True, related_name='article_favorites', to=settings.AUTH_USER_MODEL, verbose_name='收藏')),
                ('likes', models.ManyToManyField(blank=True, related_name='article_likes', to=settings.AUTH_USER_MODEL, verbose_name='点赞')),
                ('tags', models.ManyToManyField(blank=True, related_name='article_tags', to='articles.ArticleTags', verbose_name='标签')),
            ],
            options={
                'verbose_name': '文章管理',
                'verbose_name_plural': '文章管理',
                'db_table': 'articles',
                'ordering': ['-update'],
                'index_together': {('id', 'slug')},
            },
        ),
    ]
