# Generated by Django 2.2 on 2019-05-22 17:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190522_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecolumns',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 17, 9, 23, 534000), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='articles', to='articles.ArticleColumns', verbose_name='栏目'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 17, 9, 23, 535000), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='articletags',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 17, 9, 23, 535000), verbose_name='创建时间'),
        ),
    ]
