# Generated by Django 2.2 on 2019-05-24 11:28

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20190523_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=mdeditor.fields.MDTextField(verbose_name='内容'),
        ),
    ]
