# Generated by Django 2.2 on 2019-05-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_articles_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='status',
            field=models.CharField(choices=[('1', '公开'), ('2', '私密'), ('3', '草稿'), ('4', '删除')], default='1', max_length=5, verbose_name='状态'),
        ),
    ]
