# Generated by Django 2.2 on 2019-05-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20190524_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='allowreply',
            field=models.BooleanField(default=True, verbose_name='允许评论'),
        ),
        migrations.AddField(
            model_name='articles',
            name='top',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
    ]
