# Generated by Django 2.1.7 on 2019-03-21 11:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0014_auto_20190320_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': '关键字',
                'verbose_name_plural': '关键字',
            },
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 11, 42, 22, 597400)),
        ),
        migrations.AddField(
            model_name='articletag',
            name='article',
            field=models.ManyToManyField(blank=True, null=True, related_name='article_tag', to='article.ArticlePost'),
        ),
        migrations.AddField(
            model_name='articletag',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tag', to=settings.AUTH_USER_MODEL),
        ),
    ]
