# Generated by Django 2.1.7 on 2019-03-21 11:52

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20190321_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletag',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 11, 52, 18, 111400)),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='user_like',
            field=models.ManyToManyField(blank=True, related_name='articles_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articletag',
            name='article',
            field=models.ManyToManyField(blank=True, related_name='article_tag', to='article.ArticlePost'),
        ),
    ]
