# Generated by Django 2.1.7 on 2019-03-21 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_auto_20190321_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletag',
            name='article',
        ),
        migrations.AddField(
            model_name='articlepost',
            name='article_tag',
            field=models.ManyToManyField(blank=True, related_name='article_tag', to='article.ArticleTag'),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 14, 55, 58, 834000)),
        ),
    ]
