# Generated by Django 2.1.7 on 2019-03-15 17:25

import datetime
from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190314_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='body',
            field=mdeditor.fields.MDTextField(),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 17, 25, 29, 793004)),
        ),
    ]
